
var favouriteDocRef = undefined;
var hospitalIdList = undefined;

var userUid = undefined;

function getUserId() {
    firebase.auth().onAuthStateChanged(user => {
        // Check if a user is signed in:
        if (user) {
            var userUid = user.uid;
            userName = user.displayName;
            $("#name-goes-here").text(userName);

            favouriteDocRef = db.collection('userProfiles').doc(userUid).collection('favourite');
            getBookmarks();
        } else {
            console.log('User not logged in')
        }
    })
}

getUserId();


function getBookmarks() {
    firebase.auth().onAuthStateChanged(user => {
        // Check if a user is signed in:
        if (user) {
            let currentUser = db.collection("userProfiles").doc(userUid);
            currentUser.get().then(userDoc => {
                if (userDoc.exists) {

                    // Get the Array of bookmarks
                    var bookmarks = userDoc.data().bookmarks;
                    console.log(bookmarks);

                    // Get pointer the new card template
                    let newcardTemplate = document.getElementById("favouriteHospitalTemplate");

                    // Iterate through the ARRAY of bookmarked hikes (document ID's)
                    bookmarks.forEach(thisHospitalID => {
                        console.log(thisHospitalID);
                        db.collection("hospitals").doc(thisHospitalID).get().then(doc => {
                            var title = doc.data().name; // get value of the "name" key
                            var details = doc.data().details;
                            var hospitalCode = doc.data().code; //get unique ID to each hike to be used for fetching right image
                            var hospitalHour = doc.data().hours; //gets the length field
                            var docID = doc.id;  //this is the autogenerated ID of the document

                            //clone the new card
                            let newcard = newcardTemplate.content.cloneNode(true);

                            //update title and some pertinant information
                            newcard.querySelector('.card-title').innerHTML = title;
                            newcard.querySelector('.card-hour').innerHTML = hospitalHour;
                            newcard.querySelector('.card-text').innerHTML = details;
                            newcard.querySelector('.card-image').src = `./images/${hospitalCode}.png`; //Example: MSJ.png
                            newcard.querySelector('a').href = "hospital_detail.html?docID=" + docID;

                            //Finally, attach this new card to the gallery
                            document.getElementById("favourite-go-here").appendChild(newcard);
                        })
                    })
                };
            })
        }
    })
    if (document.getElementById("favourite-go-here").innerHTML.trim() == '') {
        document.getElementById("favourite-go-here").innerHTML += '<p class="py-5 my-5">You have not saved any hospital yet!</p>';
    }
}

